# Generated by Django 4.2.5 on 2023-09-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
