# Generated by Django 4.2.5 on 2023-09-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_incident_reporter_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
